Revert "Fix insert-from-values interleaved with table swaps(renames)"
This reverts commit 65af77c0c7f1e2f93d5893d1f556356b3c13837d.

The fix broke crate-qa tests:

    crate.client.exceptions.ProgrammingError: NotSerializableExceptionWrapper[ClassCastException: class io.crate.metadata.blob.BlobTableInfo cannot be cast to class io.crate.metadata.doc.DocTableInfo (io.crate.metadata.blob.BlobTableInfo and io.crate.metadata.doc.DocTableInfo are in unnamed module of loader 'app')]
    org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: ClassCastException: class io.crate.metadata.blob.BlobTableInfo cannot be cast to class io.crate.metadata.doc.DocTableInfo (io.crate.metadata.blob.BlobTableInfo and io.crate.metadata.doc.DocTableInfo are in unnamed module of loader 'app')
    at io.crate.metadata.Schemas.getTableInfo(Schemas.java:268)
    at io.crate.execution.dml.upsert.ShardUpsertRequest.<init>(ShardUpsertRequest.java:109)
    at io.crate.execution.dml.upsert.TransportShardUpsertAction.lambda$new$0(TransportShardUpsertAction.java:122)
    at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:55)
    at org.elasticsearch.transport.InboundHandler.newRequest(InboundHandler.java:245)

(cherry picked from commit d2265dc7e0b00b9ec7ecd95fbf0183c4864c4844)